# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x     
    - run: npm install
    - run: npm run test
    - name: Upload coverage folder
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: coverage

  sonarcloud:
    name: SonarCloud
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download the coverage folder
      uses: actions/download-artifact@v3
      with:
        name: coverage
        path: coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
  build:
    name: Build
    needs: sonarcloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x     
    - run: npm install
    - run: npm run build 
    - name: Upload build folder
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build

  cypress-run:
    name: E2E Test
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm start
          browser: chrome

  publish:
    name: Publish to Pages Artifacts
    needs: cypress-run
    runs-on: windows-latest
    steps:
      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: build
    
  deploy:    
    name: Deploy to Github Pages
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
  
  success_deploy:
    name: Success README
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CUSTOM_REPLACER_FILE: './deploy-success.json'

  fail_deploy:
    name: Fail README
    needs: ['sonarcloud', 'build', 'deploy']
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: Readme-Workflows/readme-replacer@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CUSTOM_REPLACER_FILE: './deploy-fail.json'
