# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        cache: 'npm'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x     
    - run: npm install

  test:
    name: Test
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - run: npm run test
        
  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - run: npm run build

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'build/'
    
  deploy:    
    name: Deploy to Github Pages
    needs: publish
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
    

